MainWidget:

<MainWidget>:
    cols: 1
    Label:
        text: root.w
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Combo Clicker"
            on_press: root.Combo_Click()
        Label:
            text: "press b to stop"
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Adventure Clicker"
            on_press: root.Adventure_Click()
        Label:
            text: "press b to stop"